### ISSUE TITLE
WATSON_TTS_URL ignored

### ISSUE THREAD

**Issue by jpvillaseca** [WASdev/sample.voice.gateway#101]
Hello,
I deployed the IBM Voice Gateway on Bluemix, with the Kubernetes deploy instructions, and Twilio.
Everything worked flawlessly.
Then, I wanted to test the gateway with the sample TTS adapter, so I changed the WATSON_TTS_URL in the deploy.json (as instructed), redeployed the server (with the new env), but the new WATSON_TTS_URL, even though it is correctly set in the media relay pod), is not used because my TTS server never receives a request.

It seems that the issue is in **voice-gateway-conversation-es.json**, **voice-gateway-conversation-multi.json**, **voice-gateway-conversation-pt.json**, because they include credentials (with their own username, password and TTS url) in many of the dialogs JSON payload.

**Comment by jfmartinez** [comment]
@jpvillaseca you are correct, if there are credentials with an url defined in the  Conversation dialog, those will take precedence over the WATSON_TTS_URL set in the `deploy.json`. Removing them from the credentials from the dialog should the problem

**Comment by jfmartinez** [comment]
Sounds like this has been resolved, I'll close the issue, re-open if you feel like you need more answers
