### ISSUE TITLE
Cloudant-View-Sample Date Format

### ISSUE THREAD

**Issue by Noah-Burrell** [WASdev/sample.voice.gateway#132]
The dates are formatted as strings without leading zeros for months, days, hours, minutes, and seconds, so the dates are sorted incorrectly in Cloudant. For example, today 6/15 is seen as earlier than 6/2, so if I calculated all of the call minutes from 6/15 onward, it would erroneously include the calls from 6/2.

**Comment by jlawwill** [comment]
I updated the code to add the leading zeros.   Thanks for catching this Noah.
