### ISSUE TITLE
Start a call programmatically?

### ISSUE THREAD

**Issue by nasht00** [WASdev/sample.voice.gateway#134]
How do I start a call programmatically?

Meaning, instead of waiting for someone to call my number, I want to trigger the call via some API.

**Comment by bpulito** [comment]
@nasht00 Hi Nathan, Voice Gateway does not currently support an API for outbound calling. This is a feature in our backlog. We are looking for customer input on this to help prioritize the feature. Please provide details on your use case and the related business opportunity if you can.

**Comment by jfmartinez** [comment]
@nasht00 With version 1.0.2.0, IBM Voice Gateway now supports an outbound calling API. 

I'm closing this issue, but feel free to open a new one if you have any more issues/questions.

Feel free to talk to us on Slack in the [IBM Cloud Technology](https://www.ibm.com/links?url=https%3A%2F%2Fslack-invite-ibm-cloud-tech.mybluemix.net%2F) team under the #ibmvoicegateway channel

**Comment by nasht00** [comment]
@jfmartinez I'm no longer active in the project, however it would be good to put here a link to this new API, so that people searching here would find relevant information.

Thanks!

**Comment by jfmartinez** [comment]
Good suggestion! More information on initiating Outbound calls through the REST API can be found [here](https://www.ibm.com/support/knowledgecenter/SS4U29/apioutboundcalls.html).
