### ISSUE TITLE
New authentication parameter, API Key, is supported?

### ISSUE THREAD

**Issue by angelescifuentes** [WASdev/sample.voice.gateway#138]
Dear Friends:
How can  I use the docker voice gateway with a new watson dialog using the new authentication parameter API Key ?

**Comment by ethilesen** [comment]
Any progress on this?

**Comment by ethilesen** [comment]
Hi, i test this and it works...

username: 'apikey',
password: "*****RhcJLwo1PDJs9L8vzVm6Puz9Wr58sZlKP****"

**Comment by jfmartinez** [comment]
@ethilesen ty for the response
@angelescifuentes 
you can also use IAM API Key with tokens,

You can use an IAM API key authentication with environment variables, in your docker deploy.yaml file, configure the following environment variables with your API key information and token service provider URL.

* Watson Assistant:
```
      WATSON_CONVERSATION_APIKEY=YOUR_API_KEY
      WATSON_CONVERSATION_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
```

* Speech to Text:
```
      WATSON_STT_APIKEY=YOUR_API_KEY
      WATSON_STT_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
```

* Text to Speech:
```
      WATSON_TTS_APIKEY=YOUR_API_KEY
      WATSON_TTS_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
```

More info on authentication: https://www.ibm.com/support/knowledgecenter/SS4U29/authentication.html

**Comment by bpulito** [comment]
@jfmartinez Can we close this one?

**Comment by ethilesen** [comment]
Sure...

Espen Thilesen
Sendt fra nettbrett....
