### ISSUE TITLE
the cf ic CLI command fails

### ISSUE THREAD

**Issue by tusharthakur1990** [WASdev/sample.voice.gateway#27]
Hello,

The cf ic login command fails: it says ic command cannot be recognized. Also, the ./pull_tag_push.sh script is not able to fetch/determine the repository, the $REPO variable returns empty string. Can you suggest a solution for it? I am guessing the cl ic has been deprecated. 

Thanks.

**Comment by jfmartinez** [comment]
Hey, 

Sorry for the inconvenience, looks like `cf ic` was replaced with `bx ic`just recently.

If you don't have `bx ic` CLI tool installed, you can follow a guide to install it - [Setting up the IBM Containers CLI](https://console.ng.bluemix.net/docs/containers/container_cli_cfic_install.html)

Also if you haven't used the IBM Containers Service before will need to login as well - [IBM Containers CLI Login](https://console.ng.bluemix.net/docs/containers/container_cli_login.html)

In the mean time our script uses the `cf ic` CLI tool, but I'm working on a fix on this branch: `issue-27-cfic-bxic`. As a temporary fix, you can pull the changes I've made following the steps here:

1. Change directory to `sample.voice.gateway`
2. Fetch the branches:

```
git fetch origin
```

3. Switch branches:

```
git checkout -b issue-27-cfic-bxic
```

4. Follow the instructions from

**Comment by tusharthakur1990** [comment]
Awesome, thank you.

**Comment by jfmartinez** [comment]
If you have anymore issues related to the script feel free to re-open this issue.
