### ISSUE TITLE
Change the Speech to Text Model

### ISSUE THREAD

**Issue by JRJIMENEZ** [WASdev/sample.voice.gateway#33]
Hi,

Where can I change the Speech to text Model?. By default the service transcribe english interactions but I need to make an solution sample that understand other languages, not only english.

Thank you.

**Comment by bpulito** [comment]
You can modify the model through Docker environment variables. If you go here:

https://www.ibm.com/support/knowledgecenter/SS4U29/config.html

You will see reference to this variable for instance:

WATSON_STT_MODEL_CUSTOMIZATION_ID

**Comment by JRJIMENEZ** [comment]
Thanks so much. it works!!

**Comment by bpulito** [comment]
Great. Also, I should have mentioned that you can modify all the STT and TTS configuration from the Conversation now. This link explains how: 
https://www.ibm.com/support/knowledgecenter/SS4U29/dynamicspeech.html
