### ISSUE TITLE
Makes Scripts Language Neutral

### ISSUE THREAD

**Issue by jfmartinez** [WASdev/sample.voice.gateway#34]
We've had a few questions on dwAnswers where the developers had their machines in non-English and the scripts will not work because we expect the output from the Bluemix CLI to be in English.

Workaround for now would be to execute the command by changing the language inline:

```
LC_ALL=en_US ./pull_tag_push.sh
LC_ALL=en_US ./deploy.sh
```

**Comment by jersonjunior** [comment]
I have the same problem and using your tip the error still remains:

LC_ALL=en_US ./pull_tag_push.sh
--------------------------------------------------------
  Confirming you are logged in...


API endpoint:   https://api.ng.bluemix.net (API version: 2.54.0)
Region:         us-south
User:           
Account:        
Org:            
Space:          dev
**Unable to determine the repository:**

**Comment by jfmartinez** [comment]
@jersonjunior 

Hey, can you check if English is installed as a locale?
```bash
locale -a | grep en_US
```
You should see an output similar to this:
```bash
en_US
en_US.ISO8859-1
en_US.ISO8859-15
en_US.US-ASCII
en_US.UTF-8
```

If no `en_US` appears, you can install it using `locale-gen`:
```bash
locale-gen en_US
```

**Comment by jersonjunior** [comment]
locale -a | grep en_US
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8

**Comment by jfmartinez** [comment]
If you login with `bx login` and `bx ic init` does it work fine for you?

**Comment by jfmartinez** [comment]
Closing since the IBM Container service was deprecated, those scripts won't work anymore.
