### ISSUE TITLE
incorrect parameter in vgw-deployment.json

### ISSUE THREAD

**Issue by jaumemir** [WASdev/sample.voice.gateway#57]
This version still contains the old parameter "RTP_RELAY_LOGLEVEL" instead of "MEDIA_RELAY_LOG_LEVEL"

**Comment by jaumemir** [comment]
@bpulito ^

**Comment by jaumemir** [comment]
Also parameter "RTP_RELAY_HOST" instead of "MEDIA_RELAY_HOST"

**Comment by bpulito** [comment]
Looking at this now. Thx

**Comment by jfmartinez** [comment]
This was fixed on: https://github.com/WASdev/sample.voice.gateway/commit/dd09f08795368bbc40aeb889d389a61ad4bc7129
