### ISSUE TITLE
SVT: Defect:Update docker-compose.yml to include volumes as a comment

### ISSUE THREAD

**Issue by rumanaHaque** [WASdev/sample.voice.gateway#81]
While testing the multi-tenant voice gateway setup using docker - as given in this link
https://www-03preprod.ibm.com/support/knowledgecenter/SS4U29/multitenancydeploy.html
one of the steps is to update the docker-compose.yml with this value.
services:
   sip.orchestrator:
     ...
     volumes:
       - $PWD:/vgwConf/

According to the instructions, I did update with the value, but the "volumes" was one space off,
which resulted in the following error.
[root@aussvt024 docker]# docker-compose up
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 4, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 24, column 6
[root@aussvt024 docker]# vi docker-compose.yml

In order to prevent these type of errors, it would be best if the volumes was added as part of sip.orchestrator, but left as a comment - so user can uncomment when needed.
For example - as given here
media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
  environment:# Uncomment the following three lines to enable call recording
      #- ENABLE_RECORDING=true
    **#volumes:
#- $PWD/recordings:/vgw-media-relay/recordings**

Have a similar comment for the sip.orchestrator for the volumes section.
This is the link for the file
https://github.com/WASdev/sample.voice.gateway/blob/master/docker/docker-compose-self-service.yml

**Comment by rumanaHaque** [comment]
After updating the docker-compse.yml file, used this command to start the test.
[root@aussvt024 docker]# docker-compose up
Recreating voice-gateway-mr ...
Recreating voice-gateway-mr
Recreating voice-gateway-so ...
Recreating voice-gateway-so ... done
Attaching to voice-gateway-mr, voice-gateway-so
voice-gateway-mr    | [INFO] rtp-relay-cli: Media Relay - v1.0.0.3d
voice-gateway-mr    | [INFO] rtp-relay-cli: CWSMR0016I: This product is licensed for development use. The full license terms can be viewed here: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-MCAO-AJTLXM&popup=n&title=IBM%20Voice%20Gateway
voice-gateway-mr    | [INFO] RtpSessionManager: CWSMR0001I:  The Media Relay is available to serve calls. Address = 9.37.249.193, Port = 8080, UDP port range = 16384-16394
voice-gateway-so    | Launching defaultServer (WebSphere Application Server 17.0.0.2/wlp-1.0.17.cl170220170523-1818) on IBM J9 VM, version pxa6480sr4fp1-20170215_01 (SR4 FP1) (en_US)
voice-gateway-so    | [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.

**Comment by bpulito** [comment]
@rumanaHaque Can this now be closed?
